@startuml conceptual_model
Робот -- "Система управления": связывается
Робот -- Камера: опрашивает
Робот -- Пользователь
Робот -- Команда: Исполняет
Камера -- Сервер: запрашивает
Сервер -- Робот: указывает
Робот -- Сервер: запрашивает зарядку
Сервер -- Робот: дает ответ о поездке до станции
Сервер -- Камера: задает путь
Камера -- Робот: следит и указывает маршрут


@enduml
